### ISSUE TITLE
could not find: "Registry.nsh"

### ISSUE THREAD

**Issue by naming1086** [WindyPigeon/portable-app-launcher-collection#1]
i follow the video https://www.youtube.com/watch?v=SBjBqg5TJsc
but show the error, like the bottom png, i need u help
![image](https://user-images.githubusercontent.com/18303279/216095180-52e0e2d6-9a9b-40b1-b02a-d51b11cd0f09.png)
![image](https://user-images.githubusercontent.com/18303279/216095283-e4ae8b93-e35f-4d39-bf63-73592c565938.png)

**Comment by naming1086** [comment]
ok i know it, i will do it the follow way tomorrow
![image](https://user-images.githubusercontent.com/18303279/216100846-44a49fea-63c7-482f-8b33-d3240e4d84da.png)

**Comment by WindyPigeon** [comment]
Maybe you have to download registry.dll from:
https://nsis.sourceforge.io/Registry_plug-in
Put it into Other/Source/Plugins

I use NSISPortable from PortableApps.com for my work and this plugin is
included in  NSISPortable. I didn't mention it because I think it's
included in all standard NSIS distributions. I'll update the docs with this
information later. Thanks for reminding me.
